alias bip='ssh -i ~/workspace/bip/keys/bi-emr-key.pem hadoop@emr-master'
alias bipc='scp -i ~/workspace/bip/keys/bi-emr-key.pem'
alias redshift='psql -h data-science.cxe2dqskszui.us-west-2.redshift.amazonaws.com -p 5439 dev root'
alias test-redshift='psql -h data-science-test2.cxe2dqskszui.us-west-2.redshift.amazonaws.com -p 5439 dev root'
alias clip='xclip -sel clip'
