#!/bin/bash

basepath="/usr/local/lib/drupal"

sub="."

here="`pwd`"

if [ "$1" ]
 then
   sub="modules"
   ln -s $basepath/$sub/$1 .
   exit
fi

read -p "Are you sure you want delete 'sites' from $here and make links to Drupal files at $basepath$cvs ? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
  echo "OK. Continuing."
else
  echo "Aborting."
  exit 0
fi


for f in `ls -A $basepath/$sub`
 do 
   ln -s $basepath/$sub/$f $f
 done

rm -r sites
cp -R $basepath/$sub/sites .
mkdir sites/all/modules
mkdir sites/all/themes
mkdir sites/default/files
chmod a+w sites/default/files
cp sites/default/default.settings.php sites/default/settings.php
chmod a+w sites/default/settings.php


