#!/bin/bash

if [ -z $1 ]; then
  echo "Usage: $0 example.com [lenght=18]"
  exit 0
fi

if [ ! -c ~/.config/genpass_salt ]; then
  mkdir ~/.config
  echo `head -c9 /dev/urandom |base64` > ~/.config/genpass_salt
fi
salt=`cat ~/.config/genpass_salt`

site=$1
len=18
if [ ! -z $2 ]; then
  len=$2
fi

echo 'Enter passphrase:'
stty_orig=`stty -g` 
stty -echo
read passphrase
stty $stty_orig

echo "$site$passphrase$salt"|sha1sum |base64|cut -c1-$len
