<?php

/**
 * Prints nice output, for browser or CLI, whether logged in or not.
 */
function nsm($var, $arg = NULL) {
  if (user_access('access devel information')) {
    dsm($var, $arg);
  } else {
    drupal_set_message(var_export($var, TRUE));
  }
}

/**
 * Handles cuaght exceptions
 */
function ncatcher($e, $var, $caller = 'previous function call.') {
    nsm($e, 'Exception in '. $caller);
    nsm($var);
    nsm(debug_backtrace());
}

/**
 * Delete nodes fast based on a node table column. Checks for query errors.
 * @todo add count feedback
 */
function nfastdelete($value, $column = 'type') {
  $q = "SELECT nid FROM node WHERE $column = :val LIMIT 100";

  try {
    $result = db_query($q , array(':val' => $value));
  } catch (Exception $e) {
    var_export($e);
    var_export($result);
    return;
  }
  while ($nids = $result->fetchCol()) {
    node_delete_multiple($nids);
    $result = db_query($q , array(':val' => $value));
  }
}

/**
 * Returns TRUE if we are running from Drush ev or scr or some other CLI.
 */
function ndrush() {
  return php_sapi_name() == 'cli'
}
